language: node_js
os:
    - linux
    - osx
node_js:
    - "4"
    - "8"
before_script:
    - npm install grunt-cli -g
env:
    - CXX=g++-4.8
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-4.8

before_deploy:
    - git config user.email "travis@travis.travis"
    - git config user.name "Travis"
    - git clone https://github.com/concierge/aws-deploy.git deploy || true
    - mv deploy/scripts scripts || true
    - mv deploy/appspec.yml appspec.yml || true
    - zip -r Concierge.zip core scripts main.js package.json appspec.yml || true
    - mkdir -p "dpl_cd_upload"
    - mv Concierge.zip dpl_cd_upload/Concierge.zip || true

deploy:
    - provider: npm
      api_key: $NPM_API_KEY
      email: $NPM_EMAIL_ADDRESS
      on:
        repo: concierge/Concierge
        branch: master
        node: "8"
        condition: "$TRAVIS_OS_NAME = linux"
    - provider: s3
      access_key_id: $AWS_ACCESS_KEY
      secret_access_key: $AWS_SECRET_KEY
      local_dir: dpl_cd_upload
      bucket: concierge-demo
      region: us-west-2
      skip_cleanup: true
      acl: public_read
      detect_encoding: true
      on:
        repo: concierge/Concierge
        branch: master
        node: "8"
        condition: "$TRAVIS_OS_NAME = linux"
    - provider: codedeploy
      access_key_id: $AWS_ACCESS_KEY
      secret_access_key: $AWS_SECRET_KEY
      bucket: concierge-demo
      key: Concierge.zip
      bundle_type: zip
      application: ConciergeDemo-App
      deployment_group: ConciergeDemo-DepGrp
      region: us-west-2
      on:
        repo: concierge/Concierge
        branch: master
        node: "8"
        condition: "$TRAVIS_OS_NAME = linux"
